PluginAndPartners/cart-woocommerce

- includes/helpers/WC_WooMercadoPago_Helpers_CurrencyConverter.php
Adicionado tratamento de erro da API de conversão de moeda
> Adicionado tratamento de erro da API de conversão de moeda (Bugfix/PLUG-649)

- CHANGELOG.md
- changelog.log
- readme.txt
> Added changelog

- i18n/languages/woocommerce-mercadopago.pot
- includes/module/WC_WooMercadoPago_Module.php
Exclusão do código método de envio (Bugfix/PPP-897)
https://mercadolibre.atlassian.net/browse/PPP-897
> Exclusão do código método de envio (Bugfix/PPP-897)

- includes/payments/hooks/WC_WooMercadoPago_Hook_Abstract.php
Aplicando correção
[Original request](https://github.com/mercadopago/cart-woocommerce/pull/256/commits/b0eb836567775d798c795d272a7f7d476d379657)
> Apply fix of jereef - Added validation for Payment Gateway

- CHANGELOG.md
- changelog.log
- readme.txt
- woocommerce-mercadopago.php
Conflicts:
i18n/languages/woocommerce-mercadopago-es_AR.mo
i18n/languages/woocommerce-mercadopago-es_AR.po
i18n/languages/woocommerce-mercadopago-es_CL.mo
i18n/languages/woocommerce-mercadopago-es_CL.po
i18n/languages/woocommerce-mercadopago-es_CO.mo
i18n/languages/woocommerce-mercadopago-es_CO.po
i18n/languages/woocommerce-mercadopago-es_ES.mo
i18n/languages/woocommerce-mercadopago-es_ES.po
i18n/languages/woocommerce-mercadopago-es_MX.mo
i18n/languages/woocommerce-mercadopago-es_MX.po
i18n/languages/woocommerce-mercadopago-es_PE.mo
i18n/languages/woocommerce-mercadopago-es_PE.po
i18n/languages/woocommerce-mercadopago-es_UY.mo
i18n/languages/woocommerce-mercadopago-es_UY.po
i18n/languages/woocommerce-mercadopago-es_VE.mo
i18n/languages/woocommerce-mercadopago-es_VE.po …
> Created new version 4.6.0

- includes/module/WC_WooMercadoPago_Configs.php
> check in same base... lower

- includes/module/WC_WooMercadoPago_Credentials.php
Removido PSE e PIX do CHO OFF.
https://mercadolibre.atlassian.net/browse/PPP-1263
> Removed payments methods in option custom checkout OFF - Bugfix/PPP- 1263

- i18n/languages/woocommerce-mercadopago.pot
- includes/module/class-wc-woomercadopago-configs.php
- includes/notification/class-wc-woomercadopago-notification-abstract.php
- Register old and new api callbacks
> transform class name and add old format api call

- CHANGELOG.md
- changelog.log
- includes/module/config/class-wc-woomercadopago-constants.php
- package-lock.json
- package.json
- readme.txt
- woocommerce-mercadopago.php
- Compatibility with old notification urls
> Release 5.0.1

- includes/module/class-wc-woomercadopago-module.php
- Check if is object before call method_exists
> :bug: check is object before check method

- includes/module/class-wc-woomercadopago-configs.php
- includes/module/preference/class-wc-woomercadopago-preference-abstract.php
- includes/notification/class-wc-woomercadopago-notification-abstract.php
- includes/notification/class-wc-woomercadopago-notification-ipn.php
[https://mercadolibre.atlassian.net/browse/PPP-1450](https://mercadolibre.atlassian.net/browse/PPP-1450)
> Updated metadata and notification url for core notifier

- includes/module/class-wc-woomercadopago-module.php
- includes/module/preference/class-wc-woomercadopago-preference-abstract.php
Adding source_news type to reduce the number of notifications that came from the API
> [FIX] - Adding source_news ipn type

- includes/helpers/cryptography/class-cryptography.php
- includes/helpers/log/class-log.php
- includes/helpers/log/index.php
- includes/module/class-wc-woomercadopago-module.php
- includes/module/preference/class-wc-woomercadopago-preference-abstract.php
- includes/notification/new/class-wc-woomercadopago-notification.php
- Fix Response
- External Reference
- Store URL
- Order created at timestamp
- Changing obj to string
- Fixing with new encrypt
- Fix post endpoint
> [FIX] Core Notifier Endpoint

- includes/notification/new/class-wc-woomercadopago-notification.php
> [FIX] - Log Core Notifier

- includes/notification/new/class-wc-woomercadopago-notification.php
Essa função foi introduzida por causa do comportamento do Woocommerce, onde ao criar um pedido ele ja gera o status especifico e por causa disso o Core Notifier não enviava a request para alterar o seu status. Nessa caso, ele irá verificar que sera o primeiro contato com o Core e irá adicionar dados para que o pedido seja atualizado pelo Core.
`
if ( $this->should_update_meta_data( $order) ) {
$this->update_mp_meta_data( $order, $data['payment_id'] );
}
`
> Function that update meta_data

- includes/notification/new/class-wc-woomercadopago-notification.php
Removing some debug logs and censor Hmac on response log
Before changes:
After changes:
> [FIX] - Logs

- .husky/pre-commit
- includes/module/class-wc-woomercadopago-module.php
- package.json
Essa PR serve para que seja verificado o code style do PHP antes do código ser commitado. A imagem abaixo mostra que 
existe um arquivo com 2 erros e o commit não é realizado. Isso evita que o código fora do padrão suba caso esqueçamos de executar esse script, poupando nosso tempo.
<p align="center">
</p>
> Automatizando verificação de code style do PHP

- includes/payments/class-wc-woomercadopago-custom-gateway.php
> fix(wallet button): fixed default to yes

- includes/module/preference/class-wc-woomercadopago-preference-abstract.php
- Utilização dos campos city_name e state_name já existentes em shipments.
- Criação dos campos city_name state_name e country_name dentro do metadata para envio de dados de billing_address.
- Criação do campo seller_website dentro do metadata para envio da url da loja
- Criação de array user no metadata para envio de dados logados - user_email, user_registration_date, registered_user.
> [PPWP-2][Woo] Completitud Datos PF

- i18n/languages/woocommerce-mercadopago.pot
- includes/module/sdk/lib/class-mp.php
Removi uma chamada que era com access_token na URL na chamada de payment com Id.
> fix(header auth): 🐛 change call of payments to use access token header

- includes/payments/class-wc-woomercadopago-payment-abstract.php
> Trocando cor de fundo o alerta do modo de checkout

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Após essa PR ser misturada com a master, as próximas PRs serão criadas de acordo com o novo modelo.
> Adicionando template padrão para PRs

- assets/css/basic_checkout_mercadopago.css
https://mercadolibre.atlassian.net/browse/PLUG-1530
> Adjusted text checkout terms and conditions

- readme.txt
[IT] [Woocommerce] - Inclusión de contacto comercial en Marketplace de Woo (Growth) 
- Added link to seller contact only BR.
> feat: added link to seller contact

- readme.txt
Update (for now only available for Brazil).
> feat: update (for now only available for Brazil)

- readme.txt
atualizando o link de contato do comercial
> fix(woocommerce): 🐛 updated readme.txt commercial link

- CHANGELOG.md
- changelog.log
- includes/module/class-wc-woomercadopago-configs.php
- includes/module/config/class-wc-woomercadopago-constants.php
- includes/module/mercadopago-settings/class-wc-woomercadopago-mercadopago-settings.php
- package.json
- readme.txt
- woocommerce-mercadopago.php
alguns ajustes no carregamento do js do caronte
e passando os pagamentos ativos (estava só deixando mp na lista de pagamentos)
> Hotfix/release 5.7.0 js and gateway loads

- CHANGELOG.md
- changelog.log
- readme.txt
- woocommerce-mercadopago.php
- Instance a non-static class to call a method (Fatal error on PHP 8)
> build(v5.7.5): 📦 new version

- includes/module/config/class-wc-woomercadopago-constants.php
- package.json
ajustando um constante que faltou ¯\_(ツ)_/¯
já foi ajustado no svn
> build(v5.7.5): 📦 constant fixed

- includes/module/sdk/lib/class-mp.php
- includes/notification/class-wc-woomercadopago-notification-ipn.php
- Reajuste na notificação IPN, realizando a comparação do valor do pedido x valor pago.
- Cupom de desconto somado ao valor pago nas validações de status e valor do cupom sendo apresentado nos detalhes do pedido.
> Adjusted IPN notification to recognize discount coupon and added coupon information in order details - Bugfix/PPWP-330

- .husky/_/husky.sh
- includes/helpers/class-wc-woomercadopago-helper-current-url.php
- includes/module/class-wc-woomercadopago-module.php
- package.json
CHANGELOG:
- Added page validation
- Added validation to melidata loads only on plugin pages
> Melidata only on plugin pages

- includes/helpers/class-wc-woomercadopago-helper-links.php
Alterados links que levam ao blog com informações sobre mercado credito para México e Brasil
> Alteração dos links de mercado credito no admin

- includes/notification/class-wc-woomercadopago-notification-abstract.php
Fixed notification status partially_refunded.
> Fix/ppsoporte1 458/refound notification

- includes/module/sdk/lib/class-mp.php
! Errata: Corrige o problema do chamado 531
> fix array index access

- includes/payments/class-wc-woomercadopago-custom-gateway.php
- includes/payments/hooks/class-wc-woomercadopago-hook-custom.php
- templates/order-received/show-custom.php
Added **PCJ** and **fees** on **Order Received Page**.
**_Before:_** 
**_After:_**
> Added PCJ and taxes fees on Order Received Page

- includes/module/preference/class-wc-woomercadopago-preference-abstract.php
- package-lock.json
> fixed: zip_code without hyphen

- includes/payments/hooks/class-wc-woomercadopago-hook-custom.php
> Fixed correction v2

- includes/payments/hooks/class-wc-woomercadopago-hook-custom.php
Correction Page Received PCJ and Fees.
CHO Pro:
**CHO Custom [sem juros]:**
**CHO Custom [com juros]:**
**Boleto:**
**Pix:**
> Correction Page Received PCJ and Fees

- CHANGELOG.md
- includes/notification/class-wc-woomercadopago-notification-abstract.php
- Fixed the notification rule to allow an approved payment to be updated if the order status is on hold.
> fix: Adjust in notification rule
